title: "School Announcements - DEMO"
description: "Demo for School Announcements"
repository: schoolannouncements/schoolannouncements.github.io

exclude: [vendor]

header:
  left-header:
    - text: Home
      internal-link: index.html
    - text: Posts
      internal-link: posts.html
    - text: Documentation
      internal-link: docs/index.html

  right-header:
    - text: Privacy
      internal-link: privacy.html

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-github-metadata

